import type { Metadata } from "next";
import { cx } from "@/lib/utils";

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Footer from "@/modules/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cx(
        "antialiased",
        "selection:bg-zinc-700 selection:text-zinc-100 dark:selection:bg-zinc-100 dark:selection:text-zinc-700",
        geistSans.variable,
        geistMono.variable,
      )}
    >
      <body className="font-sans">
        {children}
        <Footer />
      </body>
    </html>
  );
}
